projects:
  todo:
    schemaPath: src/graphql/schema.json
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
